# This workflow builds and tests a CMake project on a single platform (Ubuntu)
name: CMake Build and Test on Ubuntu

on:
  # Trigger the workflow on push and pull request events for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Set the build type to Release (can be changed to Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-and-test:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Configure CMake
      - name: Configure CMake
        run: |
          # Create a build directory
          mkdir -p ${{github.workspace}}/build
          # Configure CMake with the specified build type
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      # Build the project
      - name: Build
        run: |
          # Build the project with the configured build type
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # Run tests
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          # Run tests with the configured build type
          ctest -C ${{env.BUILD_TYPE}}
