# This workflow builds and tests a CMake project on a self-hosted Ubuntu runner (WSL)
name: CMake Build and Test on Self-Hosted Ubuntu (WSL)

on:
  # Trigger the workflow on push and pull request events for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Set the build type to Release (can be changed to Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-and-test:
    # Run the job on a self-hosted runner with labels 'self-hosted' and 'ubuntu'
    runs-on: [self-hosted, ubuntu]

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure CMake
      - name: Configure CMake
        run: |
          # Create a build directory
          mkdir -p build
          # Configure CMake with the specified build type
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      # Build the project
      - name: Build
        run: |
          # Build the project with the configured build type
          cmake --build build --config ${{env.BUILD_TYPE}}

      # Run tests
      - name: Test
        working-directory: build
        run: |
          # Run tests with the configured build type
          ctest -C ${{env.BUILD_TYPE}}
