name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    env:
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      JOB_NAME: ${{ env.JOB_NAME }}
      BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Jenkins Build
        run: |
          echo "Triggering Jenkins build..."
          curl -X POST "${{ env.JENKINS_URL }}/job/${{ env.JOB_NAME }}/buildWithParameters" \
            --user "${{ env.JENKINS_USER }}:${{ env.JENKINS_API_TOKEN }}" \
            --data-urlencode "BUILD_NUMBER=${{ env.BUILD_NUMBER }}" \
            -H "Content-Type: application/x-www-form-urlencoded"
