name: Trigger Jenkins Build

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # - name: Get Commit Message
      #   id: get-commit-message
      #   run: |
      #     COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
      #     echo "Commit Message: ${COMMIT_MESSAGE}"
      #     echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV

      # - name: Read JSON Configuration
      #   id: read-json
      #   run: |
      #     if [ -f config.json ]; then
      #       JOB_NAME=$(jq -r '.buildConfig.jobName' config.json)
      #       if [ "$JOB_NAME" == "null" ] || [ -z "$JOB_NAME" ]; then
      #         echo "Error: 'jobName' not found in config.json"
      #         exit 1
      #       fi
      #       echo "JOB_NAME=${JOB_NAME}" >> $GITHUB_ENV
      #     else
      #       echo "Error: config.json file not found"
      #       exit 1
      #     fi

      # - name: Extract Job Name and Increment Build Number
      #   id: extract-and-increment
      #   run: |
      #     EXTRACTED_JOB_NAME=$(echo "${{ env.COMMIT_MESSAGE }}" | grep -oP '(?<=Activity: )\S+' || echo "")
      #     if [ -z "$EXTRACTED_JOB_NAME" ]; then
      #       EXTRACTED_JOB_NAME=${{ env.JOB_NAME }}
      #     fi
      #     echo "JOB_NAME=${EXTRACTED_JOB_NAME}" >> $GITHUB_ENV

      #     BUILD_NUMBER_FILE=".github/build-number.txt"
      #     if [ -f "$BUILD_NUMBER_FILE" ]; then
      #       BUILD_NUMBER=$(cat "$BUILD_NUMBER_FILE")
      #     else
      #       BUILD_NUMBER="00"
      #     fi
      #     BUILD_NUMBER=$(printf "%02d" $((10#$BUILD_NUMBER + 1)))
      #     echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $GITHUB_ENV

      #     echo "${BUILD_NUMBER}" > "$BUILD_NUMBER_FILE"
      #     git config user.name "github-actions"
      #     git config user.email "actions@github.com"
      #     git stash
      #     git pull --rebase
      #     git stash pop
      #     git add "$BUILD_NUMBER_FILE"
      #     git commit -m "Update build number to ${BUILD_NUMBER}" || true
      #     git push

      - name: Trigger Jenkins Build
        shell: pwsh
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL || 'http://localhost:8080' }}
          JENKINS_USER: ${{ secrets.JENKINS_USER || 'subbaramaiah_chevuru' }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN || '11da2be03c5b0dbbcfd2038946659b60c2' }}
          JOB_NAME: ${{ env.JOB_NAME || 'subbu_project' }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER || '001' }}
          DEPLOY_ENVIRONMENT: development
        run: |
          TRIMMED_JENKINS_URL=$(echo "$JENKINS_URL" | sed 's:/*$::')
          $CLEAN_JOB_NAME = [System.Web.HttpUtility]::UrlEncode($env:JOB_NAME)
          FULL_URL="${TRIMMED_JENKINS_URL}/job/${CLEAN_JOB_NAME}/build"
          Write-Output "Full URL: $FULL_URL"

          echo "curl -v \"${FULL_URL}\" \
            --user \"${JENKINS_USER}:${JENKINS_API_TOKEN}\" \
            --data-urlencode \"{BUILD_NUMBER=${BUILD_NUMBER}\" \
            --data-urlencode \"DEPLOY_ENVIRONMENT=${DEPLOY_ENVIRONMENT}\""

          Write-Output "Executing curl command:"
          curl -v \
             "${FULL_URL}" \
             --user "${JENKINS_USER}:${JENKINS_API_TOKEN}" \
             --data-urlencode "BUILD_NUMBER=${BUILD_NUMBER}" \
             --data-urlencode "DEPLOY_ENVIRONMENT=${DEPLOY_ENVIRONMENT}"

          # Curl command with hardcoded values
          Write-Output "Curl Command with Hardcoded values:"
          curl \
            "http://localhost:8080/job/subbu_project/build" \
            --user "subbaramaiah_chevuru:11da2be03c5b0dbbcfd2038946659b60c2" \
            --data-urlencode "BUILD_NUMBER=001" \
            --data-urlencode "DEPLOY_ENVIRONMENT=development"
